export interface NicheProfile {
  id: string;
  name: string;
  toneProfile: "informative" | "comedic" | "edgy" | "educational";
  hookPattern: string;
  visualVocabulary: string[];
  musicMood: string;
  targetDurationSeconds: number;
  minSceneCount: number;
  maxSceneCount: number;
  sources: string[];
  minViralityScore: number;
}

export const NICHE_PROFILES: NicheProfile[] = [
  {
    id: "tech",
    name: "Tech & AI",
    toneProfile: "informative",
    hookPattern: "Opens with a surprising AI/tech fact or question",
    visualVocabulary: ["futuristic UI", "code snippets", "circuit boards", "data visualization"],
    musicMood: "electronic, upbeat",
    targetDurationSeconds: 45,
    minSceneCount: 4,
    maxSceneCount: 7,
    sources: [
      "https://feeds.feedburner.com/TechCrunch",
      "https://www.wired.com/feed/rss",
      "https://hnrss.org/frontpage",
    ],
    minViralityScore: 0.65,
  },
  {
    id: "finance",
    name: "Finance & Markets",
    toneProfile: "edgy",
    hookPattern: "Opens with a shocking statistic about money or markets",
    visualVocabulary: ["stock charts", "dollar bills", "Wall Street", "crypto graphs"],
    musicMood: "tense, dramatic",
    targetDurationSeconds: 50,
    minSceneCount: 4,
    maxSceneCount: 8,
    sources: [
      "https://feeds.bloomberg.com/markets/news.rss",
      "https://www.ft.com/?format=rss",
    ],
    minViralityScore: 0.7,
  },
  {
    id: "science",
    name: "Science & Discovery",
    toneProfile: "educational",
    hookPattern: "Opens with a mind-bending scientific fact",
    visualVocabulary: ["space", "microscopy", "laboratory", "nature macro shots"],
    musicMood: "cinematic, orchestral",
    targetDurationSeconds: 55,
    minSceneCount: 5,
    maxSceneCount: 8,
    sources: [
      "https://www.nasa.gov/rss/dyn/breaking_news.rss",
      "https://www.sciencedaily.com/rss/top.xml",
    ],
    minViralityScore: 0.6,
  },
  {
    id: "gaming",
    name: "Gaming",
    toneProfile: "comedic",
    hookPattern: "Opens with an outrageous gaming moment or stat",
    visualVocabulary: ["gameplay footage", "neon aesthetics", "retro pixel art", "esports arena"],
    musicMood: "energetic, electronic",
    targetDurationSeconds: 40,
    minSceneCount: 3,
    maxSceneCount: 6,
    sources: [
      "https://www.ign.com/articles.rss",
      "https://kotaku.com/rss",
    ],
    minViralityScore: 0.6,
  },
  {
    id: "sports",
    name: "Sports",
    toneProfile: "edgy",
    hookPattern: "Opens with a record-breaking or controversial sports moment",
    visualVocabulary: ["stadium crowd", "athlete close-ups", "slow-motion action", "trophies"],
    musicMood: "intense, percussive",
    targetDurationSeconds: 45,
    minSceneCount: 4,
    maxSceneCount: 7,
    sources: [
      "https://www.espn.com/espn/rss/news",
      "https://bleacherreport.com/articles/feed",
    ],
    minViralityScore: 0.65,
  },
  {
    id: "health",
    name: "Health & Wellness",
    toneProfile: "informative",
    hookPattern: "Opens with a counterintuitive health fact",
    visualVocabulary: ["healthy food", "workout", "nature", "medical illustrations"],
    musicMood: "calm, uplifting",
    targetDurationSeconds: 50,
    minSceneCount: 4,
    maxSceneCount: 7,
    sources: [
      "https://www.healthline.com/rss/news",
      "https://www.medicalnewstoday.com/rss",
    ],
    minViralityScore: 0.6,
  },
  {
    id: "politics",
    name: "Politics & World Affairs",
    toneProfile: "informative",
    hookPattern: "Opens with a geopolitical tension or breaking news headline",
    visualVocabulary: ["government buildings", "world maps", "protest crowds", "flags"],
    musicMood: "serious, minimal",
    targetDurationSeconds: 55,
    minSceneCount: 5,
    maxSceneCount: 8,
    sources: [
      "https://feeds.bbci.co.uk/news/world/rss.xml",
      "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
    ],
    minViralityScore: 0.7,
  },
  {
    id: "business",
    name: "Business & Startups",
    toneProfile: "informative",
    hookPattern: "Opens with a surprising company valuation or funding round",
    visualVocabulary: ["office skyline", "pitch decks", "entrepreneurs", "product launches"],
    musicMood: "motivational, corporate",
    targetDurationSeconds: 50,
    minSceneCount: 4,
    maxSceneCount: 7,
    sources: [
      "https://feeds.feedburner.com/entrepreneur/latest",
      "https://www.businessinsider.com/rss",
    ],
    minViralityScore: 0.65,
  },
  {
    id: "entertainment",
    name: "Entertainment & Pop Culture",
    toneProfile: "comedic",
    hookPattern: "Opens with a celebrity drama or viral pop culture moment",
    visualVocabulary: ["red carpet", "movie stills", "concert footage", "social media screenshots"],
    musicMood: "pop, trendy",
    targetDurationSeconds: 40,
    minSceneCount: 3,
    maxSceneCount: 6,
    sources: [
      "https://variety.com/feed/",
      "https://deadline.com/feed/",
    ],
    minViralityScore: 0.6,
  },
  {
    id: "environment",
    name: "Environment & Climate",
    toneProfile: "educational",
    hookPattern: "Opens with a stark climate statistic or natural disaster footage",
    visualVocabulary: ["melting glaciers", "renewable energy", "wildlife", "natural disasters"],
    musicMood: "ambient, hopeful",
    targetDurationSeconds: 55,
    minSceneCount: 4,
    maxSceneCount: 8,
    sources: [
      "https://www.theguardian.com/environment/rss",
      "https://grist.org/feed/",
    ],
    minViralityScore: 0.6,
  },
  {
    id: "crypto",
    name: "Crypto & Web3",
    toneProfile: "edgy",
    hookPattern: "Opens with a massive price swing or controversial crypto event",
    visualVocabulary: ["blockchain graphics", "bitcoin logos", "trading terminals", "NFT art"],
    musicMood: "electronic, intense",
    targetDurationSeconds: 45,
    minSceneCount: 4,
    maxSceneCount: 7,
    sources: [
      "https://cointelegraph.com/rss",
      "https://decrypt.co/feed",
    ],
    minViralityScore: 0.7,
  },
  {
    id: "history",
    name: "History & Mythology",
    toneProfile: "educational",
    hookPattern: "Opens with a forgotten historical fact or myth debunked",
    visualVocabulary: ["ancient artifacts", "historical maps", "period illustrations", "ruins"],
    musicMood: "epic, orchestral",
    targetDurationSeconds: 55,
    minSceneCount: 5,
    maxSceneCount: 8,
    sources: [
      "https://www.smithsonianmag.com/rss/history-archaeology/",
      "https://historydaily.org/feed",
    ],
    minViralityScore: 0.55,
  },
  {
    id: "food",
    name: "Food & Cooking",
    toneProfile: "comedic",
    hookPattern: "Opens with a surprising food fact or outrageous recipe",
    visualVocabulary: ["food close-ups", "cooking process", "restaurant plating", "street food"],
    musicMood: "playful, jazz",
    targetDurationSeconds: 40,
    minSceneCount: 3,
    maxSceneCount: 6,
    sources: [
      "https://www.foodnetwork.com/fn-dish/rss",
      "https://www.eater.com/rss/index.xml",
    ],
    minViralityScore: 0.55,
  },
  {
    id: "travel",
    name: "Travel & Adventure",
    toneProfile: "informative",
    hookPattern: "Opens with an incredible destination or hidden gem reveal",
    visualVocabulary: ["landscape vistas", "cultural landmarks", "local markets", "adventure sports"],
    musicMood: "world music, uplifting",
    targetDurationSeconds: 50,
    minSceneCount: 4,
    maxSceneCount: 7,
    sources: [
      "https://www.lonelyplanet.com/news/feed/atom/",
      "https://nomadicmatt.com/feed/",
    ],
    minViralityScore: 0.55,
  },
  {
    id: "psychology",
    name: "Psychology & Self-Improvement",
    toneProfile: "educational",
    hookPattern: "Opens with a counterintuitive psychological insight",
    visualVocabulary: ["human brain", "mindfulness imagery", "productivity setups", "abstract emotions"],
    musicMood: "calm, focus",
    targetDurationSeconds: 50,
    minSceneCount: 4,
    maxSceneCount: 7,
    sources: [
      "https://www.psychologytoday.com/intl/node/feed/rss.xml",
      "https://jamesclear.com/feed",
    ],
    minViralityScore: 0.6,
  },
];
