"""Pydantic v2 models for the Director Agent pipeline."""
from typing import Annotated, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field


class NicheProfile(BaseModel):
    """Per-channel creative profile injected into every Director prompt.

    Ships as a built-in preset (PRD REQ-4.1.3); users can override any field.
    The `default` profile is used as a safe fallback when no profile is supplied.
    """

    model_config = ConfigDict(populate_by_name=True)

    name: str = "default"
    tone: Literal["informative", "comedic", "edgy", "educational"] = "informative"
    hookPattern: str = "opens with a compelling statement"
    visualVocabulary: list[str] = []
    captionStyle: Literal["standard", "punchy", "funny_sub"] = "standard"
    musicMood: str = "neutral"


DEFAULT_NICHE_PROFILE = NicheProfile()


class DirectorJobPayload(BaseModel):
    """Payload sent by Node.js BullMQ director queue worker."""

    model_config = ConfigDict(populate_by_name=True)

    channelId: str
    mode: Literal["worker", "creator"] = "worker"
    # Worker Mode: research report forwarded from Researcher Agent
    researchReport: Optional[dict] = None
    # Creator Mode: free-form user topic
    userPrompt: Optional[str] = None
    nicheProfile: NicheProfile = Field(default_factory=NicheProfile)
    targetSceneCount: int = Field(8, ge=1, le=20)
    targetDurationSeconds: int = Field(40, ge=10, le=3600)
    language: Literal["en", "pl", "de", "fr", "es"] = "en"
    voiceId: str = "default"


class OutlineItem(BaseModel):
    """One bullet in a 5-point outline generated by the cheap model."""

    model_config = ConfigDict(populate_by_name=True)

    sequenceNumber: int
    title: str
    keyPoint: str


class StoryboardGenerationResult(BaseModel):
    """Envelope returned by DirectorJobHandler.run()."""

    model_config = ConfigDict(populate_by_name=True)

    channelId: str
    # Populated after full generation
    storyboard: Optional[dict] = None
    # Populated in Creator Mode before approval
    outline: Optional[list[OutlineItem]] = None
    awaitingApproval: bool = False
    error: Optional[str] = None
