"""Pydantic v2 models for FEATURE-07 — Quality Gates."""
from typing import Literal, Optional

from pydantic import BaseModel, ConfigDict, Field


class QualityIssue(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    type: Literal[
        "black_frames",
        "frozen_frames",
        "audio_clipping",
        "low_bitrate",
        "slideshow_risk",
    ]
    severity: Literal["error", "warning"]
    detail: str


class QualityReport(BaseModel):
    """Full quality analysis of a rendered video.

    Generated by PostRenderAnalyzer after a successful render.
    Saved to projects.post_render_quality (JSONB) and projects.render_quality_score.
    """
    model_config = ConfigDict(populate_by_name=True)

    passed: bool
    overallScore: float = Field(ge=0.0, le=1.0)
    slideshowRiskScore: float = Field(ge=0.0, le=1.0)
    durationSeconds: float
    resolutionWidth: int
    resolutionHeight: int
    videoBitrateKbps: float
    audioBitrateKbps: float
    audioLoudnessLUFS: float
    audioTruePeakDBFS: float = -23.0
    blackFrameCount: int
    frozenFrameCount: int
    issues: list[QualityIssue] = Field(default_factory=list)
    analyzedAt: str
