"""Pydantic v2 models for FEATURE-07 — Quality Gates."""
from typing import Literal, Optional

from pydantic import BaseModel, ConfigDict, Field

# ── Pre-render asset validation models ────────────────────────────────────────


class AssetToValidate(BaseModel):
    """One asset to validate in POST /api/quality/validate-assets."""
    model_config = ConfigDict(populate_by_name=True)

    sceneId: str
    assetUrl: str                                       # presigned HTTPS URL
    assetType: Literal["video", "audio"]
    expectedMinDurationSeconds: Optional[float] = None  # from scene.durationInSeconds


class AssetValidationResult(BaseModel):
    """FFprobe result for one scene asset."""
    model_config = ConfigDict(populate_by_name=True)

    sceneId: str
    assetType: Literal["video", "audio"]
    valid: bool
    codec: Optional[str] = None
    durationSeconds: Optional[float] = None
    error: Optional[str] = None


class AssetValidationReport(BaseModel):
    """Batch result returned by POST /api/quality/validate-assets."""
    model_config = ConfigDict(populate_by_name=True)

    allValid: bool
    results: list[AssetValidationResult]


# ── Post-render quality report models ─────────────────────────────────────────


class QualityIssue(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    type: Literal[
        "black_frames",
        "frozen_frames",
        "audio_clipping",
        "low_bitrate",
        "slideshow_risk",
    ]
    severity: Literal["error", "warning"]
    detail: str


class QualityReport(BaseModel):
    """Full quality analysis of a rendered video.

    Generated by PostRenderAnalyzer after a successful render.
    Saved to projects.post_render_quality (JSONB) and projects.render_quality_score.
    """
    model_config = ConfigDict(populate_by_name=True)

    passed: bool
    overallScore: float = Field(ge=0.0, le=1.0)
    slideshowRiskScore: float = Field(ge=0.0, le=1.0)
    durationSeconds: float
    resolutionWidth: int
    resolutionHeight: int
    videoBitrateKbps: float
    audioBitrateKbps: float
    audioLoudnessLUFS: float
    audioTruePeakDBFS: float = -23.0
    blackFrameCount: int
    frozenFrameCount: int
    issues: list[QualityIssue] = Field(default_factory=list)
    analyzedAt: str
